### ISSUE TITLE
Deprecation clarification

### ISSUE THREAD

**Issue by samirpramanik** [adjust/cordova_sdk#101]
Hello,

I am using adjust 4.14. Could you let me know if there are any functionalities in 4.14 which would be deprecated in the near future with the new releases that could impact my integration?

**Comment by uerceg** [comment]
Hi @samirpramanik 

There are no features which are going to be deprecated in newer SDK versions while SDK is still within same major version number (currently v4). When ever certain SDK versions are decided to be deprecated on our end, it's mostly because certain features which new versions contain are considered to be important and needed to be used, thus advising the update to those version(s). For example, now that Google announced sunset of delivery of referrer information via `INSTALL_REFERRER` intent mechanism, all people should update to Adjust SDK version(s) which are supporting new install referrer API as a new way of getting this information. Stuff like that.

Also, each of the update doesn't have breaking API changes and is backwards compatible within same major version. So in case you update your SDK version to newer than 4.14, there should not be breaking changes in your SDK integration and all the features you used should simply continue to work as they so far.

In case you have any other questions, feel free to ping.

Cheers

**Comment by samirpramanik** [comment]
Hi, thanks for the information. Much appreciated. I have one query though. As you mentioned :

> For example, now that Google announced sunset of delivery of referrer information via INSTALL_REFERRER

Could you please let us know from which version onwards have you migrated from INSTALL_REFERRER to the new API. I read in one of your replies on the android sdk that Adjust SDK is updated to work with the new referrer API since 4.12.0.(link - [](https://github.com/adjust/android_sdk/issues/406) ) But, we are using the cordova approach for this SDK. So, how do we change to the new API.

**Comment by uerceg** [comment]
When it comes to install referrer API, you should be on a safe ground with 4.14.0 version in your app. For the reference: https://github.com/adjust/cordova_sdk/blob/v4.14.0/plugin.xml#L58

So that version of our SDK already automagically under the hood imports install referrer API dependency and uses it once SDK runs in your Android app.

You can also easily double check if all works well if you:

1. Uninstall app from your test device.
2. Set SDK to sandbox and log level to verbose.
3. Install and run the app with this SDK setup and check the logs.

You should see that next to `session` and `attribution` packages SDK will send in this run, there should also be one named `sdk_click` in whose payload you should see parameter with value `source=install_referrer`. If that's the case, things should be set up properly.
