### ISSUE TITLE
setTransactionDate in ios 

### ISSUE THREAD

**Issue by ShimshonMarketing66** [adjust/cordova_sdk#132]
Hi 
Im tryning to add the Subscription tracking after some purchase.
I dont see anything in my adjust dashboard of activation event or something else that in common of the subscription.
after contact the adjsut support they told me the date is invalid.
if someone have any idea how to send the param in the function subscription.setTransactionDate(transactionDate)

Im using the inapppurchase 2 plugin if it can help 

Thank you for help

**Comment by uerceg** [comment]
Hi @ShimshonMarketing66 

And sorry for a delay in responding. Are you still facing this issue? If yes, can you explain maybe which API are you invoking to get transaction date which you're passing to `setTransactionDate` method?

**Comment by ShimshonMarketing66** [comment]
Hi @uerceg 

`
var purchaseTime = new Date().toString();
var subscription = new AdjustAppStoreSubscription(price, currency, transactionId, receipt);
subscription.setTransactionDate(purchaseTime);
`

**Comment by uerceg** [comment]
Hi @ShimshonMarketing66,

As far as `AdjustAppStoreSubscription` objection creation is concerned, seems like things should be working. But definitely makes more sense to move this troubleshooting from here to our support team because they are definitely best address to check what might be happening behind the scenes. Subscription tracking has a few moving pieces behind the scenes (not just implementation in your app and invoking SDK API) - enabling subscription tracking feature in dashboard, proper dashboard set up of all the things we need to perform verification of the subscriptions etc. So I would definitely advise you to send this question either to your dedicated account manager in case you have one, or if not, feel free to send question about this (and feel free to reference this GitHub issue in the email) to support@adjust.com.

Cheers
