### ISSUE TITLE
[ERROR] An error occurred while running subprocess cordova.

### ISSUE THREAD

**Issue by vergelh** [adjust/cordova_sdk#143]
Buenas alguien podría ayudarme por favor, cuando intento cargar el plugin de zoom en ionic me sale este error con cordova, ya lo desístale y lo volví a instalar pero el error persiste. Espero alguien me pueda colaborar. 

Aquí el error completo.

![image](https://user-images.githubusercontent.com/74435824/124580988-4698d500-de16-11eb-852d-72875bb68e47.png)

Espero me puedan ayudar con esto.

**Comment by uerceg** [comment]
Hola @vergelh 

This issue seems to be happening upon attempt to add Zoom Cordova plugin. This is repo of Adjust SDK, so not sure if we can really help you in this case.

For the record, looking for `cordova.plugin.zoom` in `npmjs` shows [nothing](https://www.npmjs.com/package/cordova.plugin.zoom). [This](https://github.com/toptive/cordova-plugin-zoom) might be fork of the original `cordova.plugin.zoom` repo (I don't know where it is/was originally hosted) so maybe you can try adding it from there. But this is just me guessing, not sure if that's what you're looking for. 🤷‍♀️ 

Buena suerte with this.

Cheers.
