### ISSUE TITLE
TypeError: adjustConfig.hasSkad4ConversionValueUpdatedCallbackListener is not a function

### ISSUE THREAD

**Issue by psabater** [adjust/cordova_sdk#181]
# Preliminary Info

### What dependencies are you using?
 - Using [cordova_sdk](https://github.com/adjust/cordova_sdk) [4.35.1](https://github.com/adjust/cordova_sdk/releases/tag/v4.35.1)

### What are the versions of any relevant development tools you are using?
 - node 20.5.1
 - npm 9.8.0
 - Capacitor

# Report

### What unexpected behavior are you seeing?

There's a TypeError issue on call Adjust.create method with a new AdjustConfig.

```
const environment = AdjustEnvironment.Sandbox;
const token = 'XXXX';
const config = new AdjustConfig(token, environment);
Adjust.create(config);
```

```
TypeError: adjustConfig.hasSkad4ConversionValueUpdatedCallbackListener is not a function
    at Object.create ((índice):3575:26)
    at callCordovaPlugin (vendor.js:1227:39)
    at vendor.js:1320:14
    at cordova (vendor.js:1577:87)
    at AdjustOriginal.create (vendor.js:658:82)
```

![Captura de pantalla 2023-10-18 a las 11 10 51](https://github.com/adjust/cordova_sdk/assets/7089938/f8a0f019-b15f-4b22-b3ba-77695c3d768b)

### What is the expected behavior?
Adjust it's init with the config created like version 4.32.0

**Comment by uerceg** [comment]
Hi @psabater,

Thank you for the report. Is your app plain Cordova app or are you using some of the frameworks on top of it (Ionic Capacitor or something else)?

**Comment by psabater** [comment]
Hi @uerceg, I'm using Ionic Capacitor.
It seems like adjust config, on create a new class, it doesn't have  `hasSkad4ConversionValueUpdatedCallbackListener` callback function created

**Comment by uerceg** [comment]
Ah, sorry, I was late to notice that you have mentioned that you are using Capacitor. It could maybe be that the issue is that TypeScript typings which are residing in [awesome-cordova-plugins](https://github.com/danielsogl/awesome-cordova-plugins/blob/master/src/%40awesome-cordova-plugins/plugins/adjust/index.ts) repo is still not updated with all the changes which v4.35.1 has introduced ([PR still to be merged](https://github.com/danielsogl/awesome-cordova-plugins/pull/4652)).

Are you pulling the TypeScript typings in your app from that repo? (using
```ts
import { Adjust, AdjustConfig, AdjustEnvironment, AdjustLogLevel } from '@awesome-cordova-plugins/adjust/ngx';
```
import statement in your app?)

**Comment by psabater** [comment]
Oh that's the problem. For that reason the class doesn't have the correct function and fails. In order to use the plugin in version [4.35.1](https://github.com/adjust/cordova_sdk/releases/tag/v4.35.1) with typing we will have to wait for them to accept the pull request. Thank you very much!

I will close the issue and wait until it happen
