### ISSUE TITLE
Cordova SDK integration

### ISSUE THREAD

**Issue by lumierephoto** [adjust/cordova_sdk#39]
I've integrated the Adjust SDK into my project, but how do I know that it is working?

What should I look for in the logs?

Also, can you take a look into how I inserted the code to call the Adjust SDK in my index.js and if it is correct:

```
var app = {
    initialize: function() {
    this.bindEvents();
},
bindEvents: function() {
    document.addEventListener('deviceready', this.onDeviceReady, false);
},
onDeviceReady: function() {
    app.receivedEvent('deviceready');

    var adjustConfig = new AdjustConfig("APP_TOKEN", AdjustConfig.EnvironmentSandbox);

    Adjust.create(adjustConfig);
},
receivedEvent: function(id) {
    var parentElement = document.getElementById(id);
    var listeningElement = parentElement.querySelector('.listening');
    var receivedElement = parentElement.querySelector('.received');

    listeningElement.setAttribute('style', 'display:none;');
    receivedElement.setAttribute('style', 'display:block;');

    console.log('Received Event: ' + id);
 }
};
```

**Comment by uerceg** [comment]
Hi @lumierephoto and thank you for opening this issue.

As far as I see, everything looks good. My advice would be to turn log level to `verbose` so that you can see all the logs which our SDK prints. You can adapt your initialisation code to look something like this:

```js
var adjustConfig = new AdjustConfig("APP_TOKEN", AdjustConfig.EnvironmentSandbox);
adjustConfig.setLogLevel(AdjustConfig.LogLevelVerbose);
Adjust.create(adjustConfig);
```

I run example app on iPhone usually like this:

```
cordova ios clean && cordova build ios && cordova run ios --device
```

After running it, you can open Xcode, choose `Window --> Device` and check your device's logs. Here's how it looks in my case and notice red selected part which says that install has been tracked.

![screen shot 2016-04-01 at 14 55 32](https://cloud.githubusercontent.com/assets/1741635/14207444/814f8f82-f81a-11e5-97b9-d723af28e212.png)

Let me know if you need any further assistance.

Cheers

**Comment by lumierephoto** [comment]
I followed your instructions but I'm not getting any logs in the Windows -> Devices.

Here is my index.js updated with the new line of code:
    
     var app = {
         initialize: function() {
          this.bindEvents();
      },
  
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
   
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
         
        //  Adjust SDK Configure
        var adjustConfig = new AdjustConfig("dyg2nxyx2dj4
		APP TOKEN
		", AdjustConfig.EnvironmentSandbox);
        
          adjustConfig.setLogLevel(AdjustConfig.LogLevelVerbose);
          Adjust.create(adjustConfig);
       },
    
      receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
      }
    };
 

 Where are you putting this code in your app demo?

    var adjustConfig = new AdjustConfig("APP_TOKEN", AdjustConfig.EnvironmentSandbox);
    adjustConfig.setLogLevel(AdjustConfig.LogLevelVerbose);
    Adjust.create(adjustConfig);

**Comment by lumierephoto** [comment]
Also, do you have a link to your AdjustDemo Cordova project so I can see how you did it?

**Comment by lumierephoto** [comment]
This is the only log that I get in Xcode for the SDK:

2016-04-01 13:43:42.459 Solitaire[1667:73436] [CDVTimer][adjust] 2.776980ms

**Comment by uerceg** [comment]
Sure, example app is not something which is such a big secret, we're just not keeping it at the moment in the repository due to its big size. You can download it temporary from here: https://drive.google.com/file/d/0B6y4oN3t1pm4Ny1IamlLTXJhVHc/view?usp=sharing

Let me know once you have downloaded it.

**Comment by lumierephoto** [comment]
Thanks, I downloaded it.

**Comment by uerceg** [comment]
Great. Just please instead of string I wrote (`{YourAppToken}`) write actually your app token. BTW, I have edited your upper posts with code to hide your actual app token which you pasted.

**Comment by uerceg** [comment]
@lumierephoto Any update on this issue?

**Comment by uerceg** [comment]
Closing the issue due to inactivity.

@lumierephoto Feel free to reopen the issue if you still face this issue.

**Comment by NagendraMNK** [comment]
> [no longer valid link]

I am facing same issue, [CDVTimer][adjust] 0.084996ms

Could you please help me here, because of this, creat events are not working
