### ISSUE TITLE
Can't install plugin anymore (Cordova 8)

### ISSUE THREAD

**Issue by adamiprinciples** [adjust/cordova_sdk#81]
Doesn't look like the plugin is installing correctly any more... Could be since the upgrade of our build machine to OSX Mojave or XCode 10. I get the following when trying to install:

```
$ cordova plugin add https://github.com/adjust/cordova_sdk.git\#cordova-8 --verbose
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "https://github.com/adjust/cordova_sdk.git#cordova-8"
saving
Running command: npm install https://github.com/adjust/cordova_sdk.git#cordova-8 --production --save
Command finished with error code 0: npm install,https://github.com/adjust/cordova_sdk.git#cordova-8,--production,--save
Copying plugin "/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/node_modules/com.adjust.sdk" => "/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/plugins/com.adjust.sdk"
Calling plugman.install on plugin "/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/plugins/com.adjust.sdk" for platform "android
Installing "com.adjust.sdk" for android
Running command: /Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/version
Command finished with error code 0: /Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/version
Finding scripts for "before_plugin_install" hook from plugin com.adjust.sdk on android platform only.
No scripts found for hook "before_plugin_install".
Install start for "com.adjust.sdk" on android.
PlatformApi successfully found for platform android
Android Studio project detected
Beginning processing of action stack for android project...
Error during processing of action! Attempting to revert...
Failed to install 'com.adjust.sdk': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1091:7)
    at copyNewFile (/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/lib/pluginHandlers.js:258:28)
    at install (/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/adamwalker/git/pureplanet/frontend/mobile/cordova/platforms/android/cordova/node_modules/q/q.js:863:30)
```

**Comment by adamiprinciples** [comment]
This is with Android 7.1.2, Cordova 8.1.2, Mac OSX Mojave and XCode 10

**Comment by adamiprinciples** [comment]
Just ran the same build on Windows 10 and Ubuntu and everything worked so it's definitely specific to Mac OS

**Comment by uerceg** [comment]
I did a bit of quick checks on this issue. With your described environment I was also able to reproduce the issue. I am not testing this with Windows or Linux, only on Mac OS X.

It is definitely related only to Android platform on Cordova and it is related to certain changes which Cordova introduced to `android@7.1.2` platform release. If tested with any `android@7.x.y` version lower than 7.1.2, plugin from `cordova-8` branch is successfully added to the app.

I guess temporary solution would be to downgrade to `android@7.1.1` version of platform which should work, but for now still not sure what is causing this error, investigation is still ongoing. Will keep you posted.

**Comment by uerceg** [comment]
And for the rest, discussion from `cordova-android` repo: https://github.com/apache/cordova-android/issues/554

**Comment by SajAlamChaudhuri** [comment]
**I have setup FCM in iOS apache cordova app with the following**
-> cocoapods
->GoogleService-info.plist

**Using:**
Xcode 10.1
iOS 12.1
OSX 0.13.6
Installed platforms:
  ios 4.5.5
Cordova 8.0.0

cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-whitelist 1.3.3 "Whitelist

**Now, try to add fcm plugin 2.1.2 , but get following error**

$ cordova plugin add cordova-plugin-fcm
(node:5127) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: npm: Command failed with exit code 1 Error output:
npm ERR! registry error parsing json
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <HTML><HEAD>
npm ERR! <TITLE>Access Denied</TITLE>
npm ERR! </HEAD>
npm ERR! <BODY>
npm ERR! <FONT face="Helvetica">
npm ERR! <big><strong></strong></big><BR>
npm ERR! </FONT>
npm ERR! <blockquote>
npm ERR! <TABLE border=0 cellPadding=1 width="80%">
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! <big>Access Denied (authentication_failed)</big>
npm ERR! <BR>
npm ERR! <BR>
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica" SIZE=2>
npm ERR! <BR>
npm ERR! For assistance, contact your network support team.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! </TABLE>
npm ERR! </blockquote>
npm ERR! </FONT>
npm ERR! </BODY></HTML>
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/avineon/.npm/_logs/2019-03-18T11_42_15_072Z-debug.log
(node:5127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any suggestions will be appreciated
