### ISSUE TITLE
Cordova-8 branch gone missing

### ISSUE THREAD

**Issue by stinaa** [adjust/cordova_sdk#89]
Hello! We are using Cordova 7.1.0 and Cordova Android 7.1.0 and was previously relying on this plugin from `cordova-8` branch. https://github.com/adjust/cordova_sdk.git#cordova-8

This branch is now gone and we have issues building for Android with any of the latest releases.

Where did `cordova-8` branch go?

**Comment by uerceg** [comment]
Hi @stinaa.

It has been removed since Cordova seemed to have fixed the things which were making plugins not buildable for certain versions of `cordova-android` platform. I would say that things should be summed up in this issue: https://github.com/adjust/cordova_sdk/issues/81

In case you have any other questions, let us know. 

Cheers
