### ISSUE TITLE
Ionic 1 supported ?

### ISSUE THREAD

**Issue by ahmedfahmy2003** [adjust/cordova_sdk#90]
get error "AdjustConfig is not defined" on Ionic v1 project.
note: SDK and plugin installed.

**Comment by 2beens** [comment]
Hello @ahmedfahmy2003 👋 
We support Ionic versions **2 and later**, since they use Angular with `Typescript`, but we did not try to test it on Ionic v1 which uses AngularJS and thus `JavaScript`.
That being said, we do not officially support Ionic v1.

_Note_: we are not Ionic/Cordova experts, maybe you can figure out how to integrate our Cordova SDK into Ionic v1. I suppose this could work, since our Cordova SDK is written in JS.
