### ISSUE TITLE
Capacitor is major release now. Do you have plans to capacitor support?

### ISSUE THREAD

**Issue by nobu222** [adjust/cordova_sdk#91]
if not support,
Can I create custom capacitor plugin?
it will wrap iOS, Android Adjust SDK.

Do you have any special treatment for hybrid app?

**Comment by uerceg** [comment]
Hi @nobu222,

We do not have currently any plans to support this. Usually these things are request driven, meaning if we notice that there is enough interest among our current / potential clients, we would eventually consider supporting it. 

How would support for capacitor look like? Does Cordova plugin need to be tweaked a bit to support it or does it require entirely new plugin?

In any case, you are more than welcome to make it work for Capacitor, open PR and beyond any doubt, that would be the fastest way of us adding support for it, since you are probably way more knowledgeable on the topic than we currently are. 

Cheers

**Comment by nobu222** [comment]
The capacitor platform is compatible with cordova. Most cordova plugins work on the capacitor, but some do not.

adjust cordova sdk did not work.
adjust cordova probably hooks up at cordova initialization and does some processing.

The capacitor has a mechanism to add a plug-in in native code, and as the simplest method, it could be incorporated in the same way as the one to introduce adjust ios / android sdk.
We will provide sample code if necessary.

However, when fully using adjust on a hybrid app, I think that if there is a special point of caution, that process must be added. (For example, acquisition of log etc ..)

I like both the capacitor and the adjust, and I am happy to be helpful!

**Comment by nobu222** [comment]
ハイブリッドアプリにadjustを実装することに参考になりそうなリンクを見つけましたが404となっていました。
https://github.com/adjust/ios_sdk/blob/master/doc/japanese/web_views_ja.md

**Comment by uerceg** [comment]
Give this one a shot: https://github.com/adjust/ios_sdk/blob/master/doc/japanese/web_views.md

**Comment by uerceg** [comment]
Will close this one since we're not planning any actions on our side about it in time to come. In case you do come up with something, feel free to open PR and we can continue discussion on closed issue as well. Cheers.
